- name: Create dns '{{ cf_dns_entry }}' for tunnel '{{ cf_tunnel.key }}'
  command: "cloudflared tunnel route dns {{ cf_tunnel.key }} {{ cf_dns_entry }}"
  register: create_route
  failed_when:
    - create_route.rc != 0
    - "'code: 1003' not in create_route.stderr" # CNAME already exists
  changed_when: "'code: 1003' not in create_route.stderr"

- name: Show command output
  ansible.builtin.debug:
    msg: "{{ create_route.stdout }}{{ create_route.stderr }}"
