name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "**/*.yml"
    - name: Install Dependencies
      run: pip install ansible
    - name: Create ansible.cfg with correct roles_path
      run: printf '[defaults]\nroles_path=../:./' >ansible.cfg
    - name: Run ansible syntax-check
      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install auto-changelog
        run: npm install -g auto-changelog
      - name: Get current version
        run: VERSION=`cat ./VERSION`
      - name: Create changelog
        run:  auto-changelog --ignore-commit-pattern "\[ci|docu|meta\]|fixup" --starting-version $(git describe --tags `git rev-list --tags --max-count=1`) --hide-credit -o RELEASENOTES.md
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false
    needs: build
  import-role:
    runs-on: ubuntu-latest
    needs: create-release
    steps: 
    - uses: 0x022b/galaxy-role-import-action@v1
      with:
        galaxy_api_key: ${{ secrets.ansible_galaxy_apikey }}
